In [1]:
import azureml.core
from azureml.core.authentication import InteractiveLoginAuthentication
from azureml.core import Experiment, Workspace

# Check core SDK version number
print("You are currently using version", azureml.core.VERSION, "of the Azure ML SDK")
print("")

# Log In to Azure ML Workspace
interactive_auth = InteractiveLoginAuthentication(tenant_id="76f90eb1-fb9a-4446-9875-4d323d6455ad")

ws = Workspace.from_config(auth=interactive_auth)
print('Workspace name: ' + ws.name, sep='\n')

You are currently using version 1.8.0 of the Azure ML SDK

Workspace name: team20

In [31]:
from azureml.core import Dataset

# get the dataset from Azure ML Workspace
aml_dataset = Dataset.get_by_name(ws, 'train_ds', version='latest')
pdf = aml_dataset.take(1000).to_pandas_dataframe()

UserWarning: Your pandas and pyarrow versions are incompatible. Please install pyarrow>=0.12.0 for improved performance of to_pandas_dataframe. You can ensure the correct version is installed by running: pip install pyarrow>=0.12.0 --upgrade

In [38]:
import sys
sys.path.append('../scripts')
from metrics import custom_metric

In [11]:
import numpy as np
import pandas as pd

In [27]:
pdf['uplift'] = np.random.rand(pdf.shape[0])
custom_metric(pdf)

-0.67362499074691

In [30]:
import modin.pandas as pd

UserWarning: The Dask Engine for Modin is experimental.

In [32]:
data = aml_dataset.to_pandas_dataframe()

UserWarning: Your pandas and pyarrow versions are incompatible. Please install pyarrow>=0.12.0 for improved performance of to_pandas_dataframe. You can ensure the correct version is installed by running: pip install pyarrow>=0.12.0 --upgrade

In [41]:
sys.path.append('..')

In [42]:
from scripts.metrics import random_predictions

In [120]:
random_predictions(data, iterations=5)

0.7208413684359444

In [70]:
from scripts.pipeline import StupidModel, run

In [48]:
model = StupidModel()

In [71]:
import scripts

In [151]:
from importlib import reload
reload(scripts.pipeline)
from scripts.pipeline import StupidModel, run, validate_on_holdout

In [79]:
data['gender'].replace({'Ж': 0, 'М': 1, 'Не определен': np.NaN}, inplace=True)

In [96]:
kf = KFold(n_splits=4)
for a in kf.split(data):
    print(a)

(array([171758, 171759, 171760, ..., 687026, 687027, 687028]), array([     0,      1,      2, ..., 171755, 171756, 171757]))
(array([     0,      1,      2, ..., 687026, 687027, 687028]), array([171758, 171759, 171760, ..., 343512, 343513, 343514]))
(array([     0,      1,      2, ..., 687026, 687027, 687028]), array([343515, 343516, 343517, ..., 515269, 515270, 515271]))
(array([     0,      1,      2, ..., 515269, 515270, 515271]), array([515272, 515273, 515274, ..., 687026, 687027, 687028]))

In [123]:
data.sample(1000)

,CardHolder,age,cheque_count_12m_g20,cheque_count_12m_g21,cheque_count_12m_g25,cheque_count_12m_g32,cheque_count_12m_g33,cheque_count_12m_g38,cheque_count_12m_g39,cheque_count_12m_g41,...,sale_sum_6m_g25,sale_sum_6m_g26,sale_sum_6m_g32,sale_sum_6m_g33,sale_sum_6m_g44,sale_sum_6m_g54,stdev_days_between_visits_15d,stdev_discount_depth_15d,stdev_discount_depth_1m,uplift
537412,15729839,39.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.00,63.28,380.28,0.00,174.27,84.37,0.0000,0.0000,0.0000,0.405186
607270,15679613,44.0,2.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,192.35,0.00,0.00,752.18,0.00,159.99,0.0000,0.0000,0.0000,0.855960
406983,16088120,69.0,0.0,25.0,0.0,0.0,1.0,10.0,0.0,8.0,...,0.00,934.93,0.00,0.00,468.15,205.91,NaN,0.2289,0.1946,0.900720
369791,16490644,27.0,2.0,4.0,15.0,18.0,6.0,7.0,6.0,26.0,...,153.27,134.37,2778.20,137.49,2038.86,420.81,0.0000,NaN,NaN,0.287027
326614,16180572,63.0,0.0,0.0,2.0,0.0,1.0,1.0,1.0,1.0,...,119.07,0.00,0.00,150.22,68.71,0.00,0.0000,0.0000,0.0000,0.986450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669733,15710786,40.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,110.88,79.98,0.00,296.37,620.04,0.00,0.0000,0.0000,0.0000,0.683337
171542,16498213,19.0,0.0,0.0,2.0,2.0,0.0,1.0,0.0,1.0,...,74.17,0.00,79.58,0.00,84.00,267.80,0.0000,0.0000,NaN,0.041132
660751,15715044,42.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.031033
410930,16013732,43.0,0.0,1.0,1.0,0.0,1.0,4.0,1.0,1.0,...,0.00,165.77,0.00,99.99,114.48,0.00,NaN,0.3066,0.2707,0.318227
405569,16535233,51.0,0.0,9.0,16.0,14.0,0.0,6.0,2.0,21.0,...,119.25,1438.70,890.45,0.00,2042.81,1936.16,1.4142,0.1443,0.2539,0.516888

In [126]:
data.reset_index()

,CardHolder,age,cheque_count_12m_g20,cheque_count_12m_g21,cheque_count_12m_g25,cheque_count_12m_g32,cheque_count_12m_g33,cheque_count_12m_g38,cheque_count_12m_g39,cheque_count_12m_g41,...,sale_sum_6m_g25,sale_sum_6m_g26,sale_sum_6m_g32,sale_sum_6m_g33,sale_sum_6m_g44,sale_sum_6m_g54,stdev_days_between_visits_15d,stdev_discount_depth_15d,stdev_discount_depth_1m,uplift
557927,15891401,44.0,1.0,5.0,3.0,19.0,11.0,9.0,4.0,4.0,...,298.33,122.73,2888.69,406.79,157.96,486.80,0.0000,0.0000,0.0000,0.796671
417252,16438691,52.0,8.0,3.0,13.0,0.0,5.0,2.0,0.0,4.0,...,292.22,0.00,0.00,1154.57,98.97,566.37,0.0000,0.0000,0.0000,0.643042
81470,16088345,54.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.971727
524283,16175109,29.0,0.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,...,227.39,459.41,0.00,326.84,0.00,81.89,0.0000,0.0000,0.0000,0.107194
369200,15760394,43.0,0.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,...,410.59,0.00,0.00,153.53,165.87,261.37,0.0000,0.0000,0.0000,0.870299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517740,16182135,34.0,1.0,0.0,6.0,3.0,5.0,0.0,1.0,3.0,...,95.68,99.98,224.97,875.55,713.64,635.75,0.0000,0.0000,0.0000,0.101544
11486,16006515,69.0,11.0,3.0,13.0,0.0,9.0,3.0,3.0,2.0,...,796.97,0.00,0.00,401.19,55.29,0.00,0.0000,0.0000,0.0000,0.248702
67256,15919184,53.0,3.0,2.0,5.0,2.0,4.0,3.0,1.0,7.0,...,562.96,726.00,259.52,1081.41,338.48,869.32,0.0000,NaN,NaN,0.743481
269708,16128450,31.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,7.0,...,29.99,46.78,0.00,323.74,73.07,169.65,4.2426,0.1672,0.1656,0.884236
498506,15862140,32.0,2.0,3.0,0.0,2.0,1.0,4.0,1.0,1.0,...,0.00,126.66,647.91,96.99,222.34,181.27,0.0000,0.0000,0.0000,0.482222

In [125]:
data[:1000]

,CardHolder,age,cheque_count_12m_g20,cheque_count_12m_g21,cheque_count_12m_g25,cheque_count_12m_g32,cheque_count_12m_g33,cheque_count_12m_g38,cheque_count_12m_g39,cheque_count_12m_g41,...,sale_sum_6m_g25,sale_sum_6m_g26,sale_sum_6m_g32,sale_sum_6m_g33,sale_sum_6m_g44,sale_sum_6m_g54,stdev_days_between_visits_15d,stdev_discount_depth_15d,stdev_discount_depth_1m,uplift
0,16095858,47.0,3.0,22.0,19.0,3.0,28.0,8.0,7.0,6.0,...,356.67,237.25,283.84,3648.23,1195.37,535.42,1.7078,0.2798,0.3008,0.546900
1,15906620,57.0,1.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,...,62.69,58.71,87.01,179.83,0.00,122.98,0.0000,0.0000,0.0000,0.997980
2,16495466,38.0,7.0,0.0,15.0,4.0,9.0,5.0,9.0,14.0,...,533.46,83.37,593.13,1217.43,1336.83,3709.82,0.0000,NaN,0.0803,0.771201
3,16570217,65.0,6.0,3.0,25.0,2.0,10.0,14.0,11.0,8.0,...,1849.91,360.40,175.73,496.73,172.58,1246.21,0.0000,0.0000,0.0000,0.797084
4,16346871,61.0,0.0,1.0,2.0,0.0,2.0,1.0,0.0,3.0,...,168.05,461.37,0.00,237.93,225.51,995.27,1.4142,0.3495,0.3495,0.395047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,16557561,33.0,5.0,24.0,11.0,20.0,64.0,37.0,7.0,88.0,...,249.85,2909.73,2404.91,9054.78,4352.95,7029.34,0.9244,0.3224,0.3038,0.486036
996,16431589,36.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.545466
997,16179052,57.0,2.0,2.0,9.0,1.0,7.0,2.0,0.0,6.0,...,202.74,0.00,0.00,978.13,348.23,42.99,0.0000,0.0000,NaN,0.293884
998,16568014,22.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,59.00,0.00,0.00,344.56,0.00,0.00,0.0000,0.0000,0.0000,0.734413
999,16321705,46.0,2.0,1.0,11.0,3.0,6.0,4.0,3.0,5.0,...,196.42,0.00,0.00,0.00,0.00,156.37,0.0000,0.0000,0.0000,0.684451

In [130]:
data['group'].value_counts()

test       515892
control    171137
Name: group, dtype: int64

In [131]:
data.shape

(687029, 197)

In [129]:
model = StupidModel(verbose=False)
run(data.sample(100000).reset_index(drop=True), model)

({'train': 4.766204232769795,
  'test': 1.6654030485185722,
  'train_random': 1.0532445032960092,
  'test_random': 1.123937068099588},
 {'train': [4.858175811317979,
   4.8187312098496164,
   4.231526615523393,
   5.156383294388191],
  'test': [1.0759952030089768,
   0.28193259699237916,
   3.8272728079103953,
   1.4764115861625378],
  'train_random': [1.4522405625859542,
   0.8665928863106371,
   0.5784164112516722,
   1.3157281530357727],
  'test_random': [1.1350742865096695,
   0.5629187616072159,
   1.7491938280698924,
   1.0485613962115743]})

In [133]:
import azureml.core
from azureml.core.authentication import InteractiveLoginAuthentication
from azureml.core import Experiment, Workspace

# Check core SDK version number
print("You are currently using version", azureml.core.VERSION, "of the Azure ML SDK")
print("")

# Log In to Azure ML Workspace
interactive_auth = InteractiveLoginAuthentication(tenant_id="76f90eb1-fb9a-4446-9875-4d323d6455ad")

ws = Workspace.from_config(auth=interactive_auth)
print('Workspace name: ' + ws.name, sep='\n')

You are currently using version 1.8.0 of the Azure ML SDK

Workspace name: team20

In [134]:
experiment = Experiment(ws, 'full-run')
logs = experiment.start_logging()
logs.log('dataset', 'initial')
logs.log('folds', 4)
model = StupidModel(verbose=False)
res, _ = run(data, model)

In [137]:
for key, val in res.items():
    logs.log(key, val)
logs.complete()

In [109]:
import xgboost

params = {'objective': 'rank:ndcg', 'n_estimators': 100, 'eval_metric': ['ndcg', 'map']}
model = xgboost.sklearn.XGBRanker(**params)

x = data[:10000].drop(['group', 'response_att'], axis=1)
y = data[:10000]['response_att']
group = [data[:10000]['response_att'].shape[0]]

model.fit(x, y, group, verbose=True,
         eval_set=[(x, y)], eval_group=[group])

[0]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[1]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[2]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[3]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[4]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[5]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[6]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[7]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[8]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[9]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[10]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[11]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[12]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[13]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[14]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[15]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[16]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[17]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[18]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[19]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[20]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[21]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[22]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[23]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[24]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[25]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[26]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[27]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[28]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[29]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[30]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[31]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[32]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[33]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[34]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[35]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[36]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[37]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[38]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[39]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[40]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[41]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[42]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[43]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[44]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[45]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[46]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[47]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[48]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[49]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[50]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[51]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[52]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[53]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[54]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[55]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[56]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[57]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[58]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[59]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[60]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[61]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[62]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[63]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[64]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[65]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[66]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[67]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[68]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[69]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[70]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[71]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[72]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[73]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[74]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[75]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[76]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[77]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[78]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[79]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[80]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[81]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[82]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[83]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[84]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[85]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[86]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[87]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[88]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[89]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[90]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[91]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[92]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[93]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[94]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[95]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[96]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[97]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[98]	eval_0-ndcg:0.705183	eval_0-map:0.108466
[99]	eval_0-ndcg:0.705183	eval_0-map:0.108466

XGBRanker(eval_metric=['ndcg', 'map'], objective='rank:ndcg')

In [169]:
from tqdm.notebook import tqdm
from time import sleep

for i in tqdm(range(10)):
    sleep(0.1)
    print(1)

HBox(children=(FloatProgress(value=0.0, max=10.0), HTML(value='')))

1
1
1
1
1
1
1
1
1
1

In [168]:
pd.options.mode.chained_assignment = None

experiment = Experiment(ws, '5-estimators')
params = {'n_estimators': 5, 'eval_metric': ['ndcg', 'map'], 'verbose': True}

scores = []

for i in tqdm(range(10)):
    with experiment.start_logging() as logs:
        model = StupidModel(params)
        score, model = validate_on_holdout(data, model)
        for key, val in score.items():
            logs.log(key, val)
        scores.append(score)

  0%|          | 0/10 [00:00<?, ?it/s]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.871081	eval_0-map:0.301381
[1]	eval_0-ndcg:0.871355	eval_0-map:0.305234
[2]	eval_0-ndcg:0.871406	eval_0-map:0.305434
[3]	eval_0-ndcg:0.871761	eval_0-map:0.304982
[4]	eval_0-ndcg:0.878403	eval_0-map:0.325049

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.851613	eval_0-map:0.306691
[1]	eval_0-ndcg:0.858868	eval_0-map:0.32649
[2]	eval_0-ndcg:0.858863	eval_0-map:0.331309
[3]	eval_0-ndcg:0.859195	eval_0-map:0.320661
[4]	eval_0-ndcg:0.859288	eval_0-map:0.325151

 10%|█         | 1/10 [00:45<06:45, 45.02s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.871541	eval_0-map:0.304679
[1]	eval_0-ndcg:0.871867	eval_0-map:0.304587
[2]	eval_0-ndcg:0.872074	eval_0-map:0.304249
[3]	eval_0-ndcg:0.872063	eval_0-map:0.304669
[4]	eval_0-ndcg:0.875782	eval_0-map:0.318119

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.851494	eval_0-map:0.304057
[1]	eval_0-ndcg:0.86254	eval_0-map:0.320851
[2]	eval_0-ndcg:0.862721	eval_0-map:0.321954
[3]	eval_0-ndcg:0.862782	eval_0-map:0.322441
[4]	eval_0-ndcg:0.8631	eval_0-map:0.324711

 20%|██        | 2/10 [01:29<05:59, 44.99s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.870809	eval_0-map:0.30161
[1]	eval_0-ndcg:0.871278	eval_0-map:0.305773
[2]	eval_0-ndcg:0.871411	eval_0-map:0.310268
[3]	eval_0-ndcg:0.871447	eval_0-map:0.30748
[4]	eval_0-ndcg:0.876407	eval_0-map:0.322004

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.850354	eval_0-map:0.292927
[1]	eval_0-ndcg:0.855503	eval_0-map:0.310043
[2]	eval_0-ndcg:0.855844	eval_0-map:0.313535
[3]	eval_0-ndcg:0.855827	eval_0-map:0.315257
[4]	eval_0-ndcg:0.855969	eval_0-map:0.309986

 30%|███       | 3/10 [02:15<05:15, 45.06s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.87392	eval_0-map:0.308057
[1]	eval_0-ndcg:0.874321	eval_0-map:0.309785
[2]	eval_0-ndcg:0.874357	eval_0-map:0.310768
[3]	eval_0-ndcg:0.87459	eval_0-map:0.310498
[4]	eval_0-ndcg:0.879361	eval_0-map:0.326438

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.853749	eval_0-map:0.310137
[1]	eval_0-ndcg:0.862699	eval_0-map:0.333669
[2]	eval_0-ndcg:0.862849	eval_0-map:0.337391
[3]	eval_0-ndcg:0.862837	eval_0-map:0.333027
[4]	eval_0-ndcg:0.86301	eval_0-map:0.337315

 40%|████      | 4/10 [03:00<04:30, 45.05s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.871508	eval_0-map:0.3095
[1]	eval_0-ndcg:0.87174	eval_0-map:0.310099
[2]	eval_0-ndcg:0.871881	eval_0-map:0.311353
[3]	eval_0-ndcg:0.871983	eval_0-map:0.313882
[4]	eval_0-ndcg:0.877549	eval_0-map:0.326846

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.852942	eval_0-map:0.309114
[1]	eval_0-ndcg:0.86214	eval_0-map:0.32589
[2]	eval_0-ndcg:0.862336	eval_0-map:0.329487
[3]	eval_0-ndcg:0.862208	eval_0-map:0.328584
[4]	eval_0-ndcg:0.863162	eval_0-map:0.333554

 50%|█████     | 5/10 [03:45<03:45, 45.17s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.8716	eval_0-map:0.29997
[1]	eval_0-ndcg:0.8719	eval_0-map:0.301121
[2]	eval_0-ndcg:0.871935	eval_0-map:0.300944
[3]	eval_0-ndcg:0.87195	eval_0-map:0.301007
[4]	eval_0-ndcg:0.872154	eval_0-map:0.301724

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.851735	eval_0-map:0.29633
[1]	eval_0-ndcg:0.851951	eval_0-map:0.294951
[2]	eval_0-ndcg:0.852054	eval_0-map:0.29776
[3]	eval_0-ndcg:0.852468	eval_0-map:0.299492
[4]	eval_0-ndcg:0.859671	eval_0-map:0.320722

 60%|██████    | 6/10 [04:31<03:00, 45.23s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.873834	eval_0-map:0.311467
[1]	eval_0-ndcg:0.874128	eval_0-map:0.31041
[2]	eval_0-ndcg:0.874188	eval_0-map:0.311898
[3]	eval_0-ndcg:0.874295	eval_0-map:0.312254
[4]	eval_0-ndcg:0.874277	eval_0-map:0.312496

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.853047	eval_0-map:0.303658
[1]	eval_0-ndcg:0.853254	eval_0-map:0.308858
[2]	eval_0-ndcg:0.858119	eval_0-map:0.325442
[3]	eval_0-ndcg:0.858805	eval_0-map:0.324407
[4]	eval_0-ndcg:0.858814	eval_0-map:0.324416

 70%|███████   | 7/10 [05:16<02:16, 45.41s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.871316	eval_0-map:0.307194
[1]	eval_0-ndcg:0.871557	eval_0-map:0.307699
[2]	eval_0-ndcg:0.871704	eval_0-map:0.308896
[3]	eval_0-ndcg:0.871751	eval_0-map:0.310525
[4]	eval_0-ndcg:0.874783	eval_0-map:0.318491

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.848733	eval_0-map:0.28879
[1]	eval_0-ndcg:0.857914	eval_0-map:0.311468
[2]	eval_0-ndcg:0.858732	eval_0-map:0.312097
[3]	eval_0-ndcg:0.858951	eval_0-map:0.311259
[4]	eval_0-ndcg:0.864041	eval_0-map:0.323784

 80%|████████  | 8/10 [06:02<01:30, 45.45s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.872455	eval_0-map:0.301257
[1]	eval_0-ndcg:0.87282	eval_0-map:0.303452
[2]	eval_0-ndcg:0.87287	eval_0-map:0.303515
[3]	eval_0-ndcg:0.872871	eval_0-map:0.303534
[4]	eval_0-ndcg:0.873072	eval_0-map:0.304

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.848489	eval_0-map:0.293824
[1]	eval_0-ndcg:0.848818	eval_0-map:0.296618
[2]	eval_0-ndcg:0.856606	eval_0-map:0.32092
[3]	eval_0-ndcg:0.856719	eval_0-map:0.319144
[4]	eval_0-ndcg:0.860976	eval_0-map:0.327061

 90%|█████████ | 9/10 [06:48<00:45, 45.65s/it]

Обучаем модель на тестовой группе:
[0]	eval_0-ndcg:0.869988	eval_0-map:0.304213
[1]	eval_0-ndcg:0.870186	eval_0-map:0.309458
[2]	eval_0-ndcg:0.870242	eval_0-map:0.305612
[3]	eval_0-ndcg:0.870322	eval_0-map:0.305852
[4]	eval_0-ndcg:0.873958	eval_0-map:0.315422

Обучаем модель на контрольной группе:
[0]	eval_0-ndcg:0.85229	eval_0-map:0.29592
[1]	eval_0-ndcg:0.85323	eval_0-map:0.299465
[2]	eval_0-ndcg:0.863558	eval_0-map:0.317819
[3]	eval_0-ndcg:0.863539	eval_0-map:0.324916
[4]	eval_0-ndcg:0.863816	eval_0-map:0.323876

100%|██████████| 10/10 [07:34<00:00, 45.42s/it]

In [178]:
tests = np.array([el['test'] for el in scores])
tests.mean()

1.1828890894716055

In [175]:
train = np.array([el['train'] for el in scores])
train

array([1.63836307, 1.69497488, 1.59135852, 1.85736701, 1.78139901,
       1.65875129, 1.88699196, 1.52112319, 1.74211117, 1.79441011])

In [177]:
np.array([el['test_random'] for el in scores]).mean()

0.8438329998037384

In [179]:
np.array([el['train_random'] for el in scores]).mean()

0.7620998163148099

In [180]:
data

,CardHolder,age,cheque_count_12m_g20,cheque_count_12m_g21,cheque_count_12m_g25,cheque_count_12m_g32,cheque_count_12m_g33,cheque_count_12m_g38,cheque_count_12m_g39,cheque_count_12m_g41,...,sale_sum_6m_g25,sale_sum_6m_g26,sale_sum_6m_g32,sale_sum_6m_g33,sale_sum_6m_g44,sale_sum_6m_g54,stdev_days_between_visits_15d,stdev_discount_depth_15d,stdev_discount_depth_1m,uplift
0,16095858,47.0,3.0,22.0,19.0,3.0,28.0,8.0,7.0,6.0,...,356.67,237.25,283.84,3648.23,1195.37,535.42,1.7078,0.2798,0.3008,0.546900
1,15906620,57.0,1.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,...,62.69,58.71,87.01,179.83,0.00,122.98,0.0000,0.0000,0.0000,0.997980
2,16495466,38.0,7.0,0.0,15.0,4.0,9.0,5.0,9.0,14.0,...,533.46,83.37,593.13,1217.43,1336.83,3709.82,0.0000,NaN,0.0803,0.771201
3,16570217,65.0,6.0,3.0,25.0,2.0,10.0,14.0,11.0,8.0,...,1849.91,360.40,175.73,496.73,172.58,1246.21,0.0000,0.0000,0.0000,0.797084
4,16346871,61.0,0.0,1.0,2.0,0.0,2.0,1.0,0.0,3.0,...,168.05,461.37,0.00,237.93,225.51,995.27,1.4142,0.3495,0.3495,0.395047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
687024,15705403,35.0,0.0,0.0,4.0,0.0,2.0,0.0,1.0,0.0,...,669.33,111.87,0.00,330.96,1173.84,119.99,2.6458,0.3646,0.3282,0.119863
687025,16586008,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,28.01,0.0000,0.0000,0.0000,0.855074
687026,15693616,36.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,...,0.00,0.00,0.00,0.00,449.01,0.00,0.0000,NaN,NaN,0.865098
687027,15915514,37.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,...,46.72,0.00,0.00,0.00,0.00,0.00,0.0000,NaN,NaN,0.861922
687028,15817354,40.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,...,0.00,0.00,0.00,228.47,752.32,596.86,0.0000,0.0000,0.0000,0.864834